### ISSUE TITLE
顺丰脚本

### ISSUE THREAD

**Issue by EucalyZ** [zjk2017/ArcadiaScriptPublic#12]
不知道是不是我账号问题，测了两个账号giftList都返回None
172行当giftList为None时,get("giftList",[])返回None导致giftList的迭代器异常，在后方添加or []即可。
![image](https://github.com/user-attachments/assets/b14bc6a4-7af8-4a36-9eb9-3e3cfce09c5e)

**Comment by zjk2017** [comment]
py版本不再维护，那你调试好了就用你调试好的
