### ISSUE TITLE
一点万象报错

### ISSUE THREAD

**Issue by Liam-Leung** [zjk2017/ArcadiaScriptPublic#16]
签到出错 日志如下
共配置了2个账号
*****第1个账号*****
{"code":20108,"data":null,"message":"签名信息错误","success":false,"timestamp":1732848343752}
签名信息错误
帐号1签到结果:失败
*****第2个账号*****
{"code":20108,"data":null,"message":"签名信息错误","success":false,"timestamp":1732848344073}
签名信息错误
帐号2签到结果:失败
push+推送成功

**Comment by ssmengyan** [comment]
请问一点万象的token怎么抓取呢
